### ISSUE TITLE
Not working with charrtJs Doughnut chart

### ISSUE THREAD

**Issue by touch2hussain** [bebraw/Chart.js.legend#13]
var doughnutData = [
        {
          value: 300,
          color:"#F7464A",
          highlight: "#FF5A5E",
          label: "Critical"
        },

```
    {
      value: 100,
      color: "#FDB45C",
      highlight: "#FFC870",
      label: "Warning"
    }


  ];
```

$( document ).ready(function() {
        var ctx = document.getElementById("chart-area").getContext("2d");

```
    var myDoughnut1 = new Chart(ctx).Doughnut(doughnutData, {responsive : true});

    legend(document.getElementById("legend"), doughnutData1,myDoughnut1);
```

});

the legend is not working for me

**Comment by bebraw** [comment]
I set up a doughnut example. See `index.html` and `src/demo.js`. Chart.js.legend is separate from Chart.js. It just happens to operate on the same format as Chart.js.

Btw you might have a typo at your code. Maybe it should be something like this: ` legend(document.getElementById("legend"), doughnutData,myDoughnut1);`. It needs to refer to the same data at the chart.

**Comment by bebraw** [comment]
Hi,

Chart.js provides a [legend](http://www.chartjs.org/docs/#chart-configuration-legend-configuration) now.
