### ISSUE TITLE
How to use for large json with multiple property and multiple propertyValues

### ISSUE THREAD

**Issue by touch2hussain** [bebraw/Chart.js.legend#14]
[
    {
        "machineId": "1A",
        "serialNo": "123",
        "city": "",
        "Mode": "ON"
    },
    {
        "machineId": "2B",
        "serialNo": "123",
        "city": "",
        "Mode": "OFF"
    },
    {
        "machineId": "3A",
        "serialNo": "123",
        "city": "NewCity",
        "Mode": "OFF"
    },
    {
        "machineId": "1A",
        "serialNo": "123",
        "city": "",
        "Mode": "OFF"
    },
      {
        "machineId": "1A",
        "serialNo": "123",
        "city": "",
        "Mode": "Default"
    }
]

in above json, lets say i want to filter, machineId  having value "IA", and Mode having values "ON and OFF"

I tried something like 

 property: ["machineId", "Mode"],
  value: ["1A,ON,OFF"],

it did not work, Please suggest how to use the plugin in this case

**Comment by bebraw** [comment]
Can you add the Chart.js code you have? How does that data map to a chart? What do you expect to see at the legend? Understanding this will help me to provide a better solution.
