### ISSUE TITLE
Responsive?

### ISSUE THREAD

**Issue by craiglockwood** [bebraw/Chart.js.legend#8]
I see the newer version of chart.js makes charts responsive - any idea how to implement that with a legend? 

This is achieved via    

window.onload = function(){
        var ctx = document.getElementById("canvas").getContext("2d");
        window.myLine = new Chart(ctx).Line(lineChartData, {
            responsive: true
        });
    }

but this isn't referenced in the included demo.js file

**Comment by bebraw** [comment]
Looks like chart.js implements a legend in itself these days. Please take a look at `legendTemplate` in chart options at their [docs](http://www.chartjs.org/docs/).

That said you can still achieve responsiveness with `chart.js.legend`. It generates a bit of HTML that you can style through standard CSS depending on your needs.

**Comment by bebraw** [comment]
@craiglockwood Did you manage to resolve this?

**Comment by bebraw** [comment]
See [Chart.js legend](http://www.chartjs.org/docs/#chart-configuration-legend-configuration).
